CREATE TABLE IF NOT EXISTS level_data
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(100)                            NOT NULL,
    CONSTRAINT pk_level_data PRIMARY KEY (id),
    CONSTRAINT uc_level_data_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS log_data
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    level_id   BIGINT NOT NULL,
    src        VARCHAR(255)                            NOT NULL,
    message    VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_log_data PRIMARY KEY (id),
    CONSTRAINT fk_log_data_on_level FOREIGN KEY (level_id) REFERENCES level_data (id) ON DELETE CASCADE
);
